title: Furkan KALKAN
author: Furkan9534
email: furkankalkan2023@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
remote_theme: samarsault/plainwhite-jekyll # use the remote theme from GitHub
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

plainwhite:
  name: Furkan KALKAN
  tagline: Software Engineer || Software Developer || Artificial Intelligent || Data Science || Machine Learning || Data Scientist
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/profile-picture.jpeg"
  html_lang: "en"
  condensed_mobile:
    - page
    - post
  social_links:
    #twitter: samarsault
    github: Furkan9534
    linkedIn: in/furkan-kalkan

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
url: "https://furkan9534.github.io"

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
